### PR TITLE
Add support for PNLGRP syntax

### PR DESCRIPTION
**Pull request by chrjorgensen**
This change will add support for panel groups, which are used for online help for IBM i commands.

IBM i commands should always have online help to assist the user, and it is quite easy to create this using the markup language for panel groups, that IBM created several decades ago.

All panel group tags are included and will be color-coded, and attributes and values for tags used in online help will also be color-coded.

### CODE REVIEW

**Comment by barrettotte** [comment]
Oh wow very cool, I've never seen heard of this before. Thanks for your work on this!

**Comment by chrjorgensen** [comment]
You're welcome - I use it all the time and would love to have it in VS Code via your great extension... and it was fun to juggle all the regular expressions and try catching all possibilities.

And thank you for all your work with this extension!

**Comment by chrjorgensen** [comment]
Btw, I used the [Application Display Programming](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_61/rzakc/sc415715.pdf?view=kc) manual as the reference guide - chapter 20 shows how to create help panels and Appendix A shows every command/tag and attributes.

**Comment by barrettotte** [comment]
@chrjorgensen Nice, that's a good find. Thanks for the link too!

**Pull request merged**
